# Generated by Django 6.0.2 on 2026-02-24 02:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('account_name', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('bank_code', models.CharField(max_length=3)),
                ('currency', models.CharField(max_length=3)),
                ('balance', models.BigIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'account',
                'indexes': [models.Index(fields=['user'], name='account_user_id_5ee0be_idx'), models.Index(fields=['is_active'], name='account_is_acti_f1bc45_idx')],
            },
        ),
    ]
