# Generated by Django 6.0.2 on 2026-02-23 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('notification_type', models.CharField(choices=[('PAYMENT', '결제 알림'), ('NOTICE', '공지사항'), ('SYSTEM', '시스템'), ('ETC', '기타')], default='SYSTEM', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification',
                'indexes': [models.Index(fields=['user', 'is_read', 'created_at'], name='notificatio_user_id_8320d2_idx'), models.Index(fields=['notification_type', 'created_at'], name='notificatio_notific_d281eb_idx')],
            },
        ),
    ]
