# Generated by Django 6.0.2 on 2026-02-24 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('category_type', models.CharField(choices=[('INCOME', '수입'), ('EXPENSE', '지출')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'category',
                'ordering': ['category_type', 'category_name'],
                'constraints': [models.UniqueConstraint(fields=('category_type', 'category_name'), name='uniq_category_type_name')],
            },
        ),
    ]
