# Generated by Django 6.0.2 on 2026-02-24 02:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('category', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('schedule_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_type', models.CharField(choices=[('INCOME', '입금'), ('EXPENSE', '출금')], max_length=10)),
                ('memo', models.TextField(blank=True)),
                ('repeat_type', models.CharField(choices=[('DAILY', '매일'), ('WEEKLY', '매주'), ('MONTHLY', '매월'), ('YEARLY', '매년')], max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(db_column='account_id', on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='account.account')),
                ('category', models.ForeignKey(blank=True, db_column='category_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='category.category')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'schedule',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='schedule_user_id_3430cf_idx'), models.Index(fields=['repeat_type'], name='schedule_repeat__3ad25c_idx')],
            },
        ),
    ]
