# Generated by Django 6.0.2 on 2026-02-25 04:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Analysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "about",
                    models.CharField(
                        choices=[
                            ("TOTAL_EXPENSE", "총 지출"),
                            ("TOTAL_INCOME", "총 수입"),
                            ("CATEGORY_EXPENSE", "카테고리별 지출"),
                            ("CATEGORY_INCOME", "카테고리별 수입"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("WEEKLY", "매주"),
                            ("MONTHLY", "매월"),
                            ("YEARLY", "매년"),
                        ],
                        max_length=20,
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("description", models.TextField()),
                (
                    "result_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="analysis_results/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analyses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
